/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface DashboardStats {
  'clientCount' : bigint,
  'totalExpenses' : bigint,
  'totalPurchases' : bigint,
  'orderCount' : bigint,
  'totalRevenue' : bigint,
  'netProfit' : bigint,
  'transactionCount' : bigint,
}
export interface Order {
  'status' : OrderStatus,
  'total' : bigint,
  'clientId' : bigint,
  'createdAt' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Transaction {
  'date' : bigint,
  'notes' : string,
  'category' : string,
  'txType' : TransactionType,
  'amount' : bigint,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null } |
  { 'purchase' : null };
export interface _SERVICE {
  'createClient' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createOrder' : ActorMethod<[bigint, Array<OrderItem>, bigint], bigint>,
  'createTransaction' : ActorMethod<
    [TransactionType, string, bigint, string],
    bigint
  >,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getClient' : ActorMethod<[bigint], Client>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrdersByClient' : ActorMethod<[bigint], Array<Order>>,
  'getTransaction' : ActorMethod<[bigint], Transaction>,
  'getTransactionsByType' : ActorMethod<[TransactionType], Array<Transaction>>,
  'updateClient' : ActorMethod<[bigint, Client], undefined>,
  'updateOrder' : ActorMethod<[bigint, Order], undefined>,
  'updateTransaction' : ActorMethod<[bigint, Transaction], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];