/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Int,
  'unitPrice' : IDL.Int,
});
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
  'purchase' : IDL.Null,
});
export const Client = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'total' : IDL.Int,
  'clientId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'items' : IDL.Vec(OrderItem),
});
export const Transaction = IDL.Record({
  'date' : IDL.Int,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'txType' : TransactionType,
  'amount' : IDL.Int,
});
export const DashboardStats = IDL.Record({
  'clientCount' : IDL.Nat,
  'totalExpenses' : IDL.Int,
  'totalPurchases' : IDL.Int,
  'orderCount' : IDL.Nat,
  'totalRevenue' : IDL.Int,
  'netProfit' : IDL.Int,
  'transactionCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Nat, IDL.Vec(OrderItem), IDL.Int],
      [IDL.Nat],
      [],
    ),
  'createTransaction' : IDL.Func(
      [TransactionType, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrdersByClient' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getTransactionsByType' : IDL.Func(
      [TransactionType],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'updateClient' : IDL.Func([IDL.Nat, Client], [], []),
  'updateOrder' : IDL.Func([IDL.Nat, Order], [], []),
  'updateTransaction' : IDL.Func([IDL.Nat, Transaction], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Int,
    'unitPrice' : IDL.Int,
  });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const Client = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'total' : IDL.Int,
    'clientId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'items' : IDL.Vec(OrderItem),
  });
  const Transaction = IDL.Record({
    'date' : IDL.Int,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'txType' : TransactionType,
    'amount' : IDL.Int,
  });
  const DashboardStats = IDL.Record({
    'clientCount' : IDL.Nat,
    'totalExpenses' : IDL.Int,
    'totalPurchases' : IDL.Int,
    'orderCount' : IDL.Nat,
    'totalRevenue' : IDL.Int,
    'netProfit' : IDL.Int,
    'transactionCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'createClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Nat, IDL.Vec(OrderItem), IDL.Int],
        [IDL.Nat],
        [],
      ),
    'createTransaction' : IDL.Func(
        [TransactionType, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrdersByClient' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getTransactionsByType' : IDL.Func(
        [TransactionType],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'updateClient' : IDL.Func([IDL.Nat, Client], [], []),
    'updateOrder' : IDL.Func([IDL.Nat, Order], [], []),
    'updateTransaction' : IDL.Func([IDL.Nat, Transaction], [], []),
  });
};

export const init = ({ IDL }) => { return []; };